Resources:
  #
  # If you add DynamoDB Tables you must add here and in the iam-roles
  #
  BeesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName:                ${self:custom.beesTable}
      KeySchema:
        - AttributeName:        user_id
          KeyType:              HASH
        - AttributeName:        letters
          KeyType:              RANGE
      AttributeDefinitions:
        - AttributeName:        user_id
          AttributeType:        S
        - AttributeName:        letters
          AttributeType:        S
        - AttributeName:        datestr
          AttributeType:        S
        - AttributeName:        nytFrac
          AttributeType:        N
        - AttributeName:        nytMax
          AttributeType:        N
        - AttributeName:        updatedAt
          AttributeType:        S
      LocalSecondaryIndexes:
        - IndexName:            by_datestr
          KeySchema:
            - AttributeName:    user_id
              KeyType:          HASH
            - AttributeName:    datestr
              KeyType:          RANGE
          Projection:
            ProjectionType:     ALL

        - IndexName:            by_nytFrac
          KeySchema:
            - AttributeName:    user_id
              KeyType:          HASH
            - AttributeName:    nytFrac
              KeyType:          RANGE
          Projection:
            ProjectionType:     ALL

        - IndexName:            by_nytMax
          KeySchema:
            - AttributeName:    user_id
              KeyType:          HASH
            - AttributeName:    nytMax
              KeyType:          RANGE
          Projection:
            ProjectionType:     ALL

        - IndexName:            by_updatedAt
          KeySchema:
            - AttributeName:    user_id
              KeyType:          HASH
            - AttributeName:    updatedAt
              KeyType:          RANGE
          Projection:
            ProjectionType:     ALL

      BillingMode:              PAY_PER_REQUEST
      # ProvisionedThroughput:
      #   ReadCapacityUnits: 10
      #   WriteCapacityUnits: 10

  GuessesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName:                ${self:custom.guessesTable}
      KeySchema:
        - AttributeName:        user_bee_id
          KeyType:              HASH
        - AttributeName:        word
          KeyType:              RANGE
      # Only list the attributes in the key or secondary idxs
      AttributeDefinitions:
        - AttributeName:        user_bee_id
          AttributeType:        S
        - AttributeName:        word
          AttributeType:        S
      BillingMode:              PAY_PER_REQUEST

Outputs:
  BeesTableName:
    Description:        "Table holding Bees"
    Value:
      "Ref":            BeesTable
    Export:
      Name:             BeesTable-${self:custom.stage}
  GuessesTableName:
    Description:        "Table holding Guesses"
    Value:
      "Ref":            GuessesTable
    Export:
      Name:             GuessesTable-${self:custom.stage}
