Resources:
  #
  # If you add DynamoDB Tables you must add here and in the role below
  #
  ProductTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:custom.productsTable}
      KeySchema:
        -
          AttributeName: id
          KeyType:       HASH
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      # ProvisionedThroughput:
      #   ReadCapacityUnits: 10
      #   WriteCapacityUnits: 10
  UserTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:custom.usersTable}
      KeySchema:
        -
          AttributeName: handle
          KeyType: HASH
      AttributeDefinitions:
        -
          AttributeName: handle
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      # ProvisionedThroughput:
      #   ReadCapacityUnits: 10
      #   WriteCapacityUnits: 10
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.notesTable}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  TweetsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:custom.tweetsTable}
      KeySchema:
        -
          AttributeName: tweet_id
          KeyType: HASH
      AttributeDefinitions:
        -
          AttributeName: tweet_id
          AttributeType: S
        -
          AttributeName: handle
          AttributeType: S
        -
          AttributeName: retweet_count
          AttributeType: N
        -
          AttributeName: created_at
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      # ProvisionedThroughput:
      #   ReadCapacityUnits: 10
      #   WriteCapacityUnits: 10
      GlobalSecondaryIndexes:
        -
          IndexName: top-index
          KeySchema:
            -
              AttributeName: handle
              KeyType: HASH
            -
              AttributeName: retweet_count
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          # ProvisionedThroughput:
          #   ReadCapacityUnits: 10
          #   WriteCapacityUnits: 10
        -
          IndexName: tweet-index
          KeySchema:
            -
              AttributeName: handle
              KeyType: HASH
            -
              AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          # ProvisionedThroughput:
          #   ReadCapacityUnits: 10
          #   WriteCapacityUnits: 10
