Resources:
  LexyDynamoReader:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "LexyDynamoReader"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: "CloudWatch-Logger-Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - "*"
        -
          PolicyName: "Dynamo-ServiceRole-Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "dynamodb:Query"
                  - "dynamodb:BatchWriteItem"
                  - "dynamodb:GetItem"
                  - "dynamodb:DeleteItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:Scan"
                  - "dynamodb:UpdateItem"
                Resource:
                  - "arn:aws:dynamodb:us-east-1:*:table/bees-dev"
                  - "arn:aws:dynamodb:us-east-1:*:table/bees-dev/*"
                  - "arn:aws:dynamodb:us-east-1:*:table/guesses-dev"
                  - "arn:aws:dynamodb:us-east-1:*:table/guesses-dev/*"
                  
  LexyXrayRolePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "lexy-xray-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "xray:PutTraceSegments"
              - "xray:PutTelemetryRecords"
            Resource:
              - "*"
      Roles:
        - Ref: LexyDynamoReader
