Resources:
  AttachmentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # BucketName: ${self:custom.attachBucket}
      # Set the CORS policy
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000

  FooBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.fooBucket}
      # Set the CORS policy
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000


  ServerlessDeploymentBucket:
    Properties:
      AccelerateConfiguration:
        AccelerationStatus: Enabled
          
# Print out the name of the bucket that is created
Outputs:
  AttachmentsBucketName:
    Value:
      Ref: AttachmentsBucket
  FooBucketName:
    Value:
      Ref: FooBucket
